Biblioteka.Web/Controllers/AutoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Biblioteka.Web.DAL.Entities;
using Biblioteka.Web.DAL.Repositories;
using Biblioteka.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Biblioteka.Web.Controllers
{
    [Authorize(Roles = "Administrator,UserTest")]
    public class AutoriController : BaseController
    {
        public AutoriController(IRepository<Knjiga> repository, IRepository<Autor> repositoryA, IRepository<Izdavac> repositoryI)
                                        : base(repository, repositoryA, repositoryI) { }


        public IActionResult Index()
        {
            List<Autor> autori = Autori.Get().ToList();
            return View(autori);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int id)
        {
            Autori.Delete(id);
       
            Autori.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Autor autor = Autori.Get(id);
            return View(autor);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id)
        {
            //Autor autor = ;

            return View(Autori.Get(id));
        }

        public IActionResult Create()
        {
            List<Knjiga> knjige = new List<Knjiga>(); // Knjige.Get().ToList();

            AutorModel model = new AutorModel()
            {
                listaSvihKnjiga = knjige.Select(x => new SelectListItem()
                {
                    Value = x.kId.ToString(),
                    Text = x.Naslov
                })
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Autor autor)
        {
            if (autor.aId > 0)
            {
                Autori.Update(autor, autor.aId);
            }
            else
            {
                Autori.Insert(autor);
            }
            Autori.Save();
            return RedirectToAction("Index");
        }

        public IActionResult SaveNew(AutorModel autorModel)
        {
            Autor autor = new Autor()
            {
                Ime = autorModel.Ime,
                Prezime = autorModel.Prezime,
                Email = autorModel.Email,
                Biografija = autorModel.Biografija
            };

            Autori.Insert(autor);
            Autori.Save();
            /* implement later
            foreach (int knjigaId in autorModel.Knjige)
            {
                AutorKnjiga.Insert(new AutorKnjiga()
                {
                    Autor = autor,
                    Knjiga = Knjige.Get(knjigaId)
                });
            }
            Save();*/

            return RedirectToAction("Index");
        }
    }
}

Biblioteka.Web/Controllers/IzdavaciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Biblioteka.Web.DAL.Entities;
using Biblioteka.Web.DAL.Repositories;
using Biblioteka.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Biblioteka.Web.Controllers
{
    [Authorize(Roles = "Administrator,UserTest")]
    public class IzdavaciController : BaseController
    {

        public IzdavaciController(IRepository<Knjiga> repository, IRepository<Autor> repositoryA, IRepository<Izdavac> repositoryI)
                                        : base(repository, repositoryA, repositoryI) { }

        public IActionResult Index()
        {
            List<Izdavac> izdavaci = Izdavaci.Get().ToList();

            List<SelectListItem> listItems = new List<SelectListItem>
            {
                new SelectListItem() { Text = "1.item", Value = "1" },
                new SelectListItem() { Text = "2.item", Value = "2" }
            };

            ViewData.Add("items", listItems);

            return View(izdavaci);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int id)
        {
            Izdavaci.Delete(id);
            Izdavaci.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Izdavac izdavac = Izdavaci.Get(id);
            return View(izdavac);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id)
        {
            Izdavac izdavac = Izdavaci.Get(id);

            return View(izdavac);
        }


        public IActionResult Create()
        {
            List<Knjiga> knjige = new List<Knjiga>(); // Knjige.Get().ToList();

            IzdavacModel model = new IzdavacModel()
            {
                listaSvihKnjiga = knjige.Select(x => new SelectListItem()
                {
                    Value = x.kId.ToString(),
                    Text = x.Naslov
                })
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Izdavac izdavac)
        {
            if (izdavac.Id > 0)
            {
                Izdavaci.Update(izdavac, izdavac.Id);
            }
            else
            {
                Izdavaci.Insert(izdavac);
            }
            Izdavaci.Save();
            return RedirectToAction("Index");
        }

        public IActionResult SaveNew(IzdavacModel izdavacModel)
        {
            Izdavac izdavac = new Izdavac()
            {
                Ime = izdavacModel.Ime,
                Sjediste = izdavacModel.Sjediste,

            };

            Izdavaci.Insert(izdavac);
            Izdavaci.Save();
            /* implement later saving selected books while creating new Publisher
            foreach (int knjigaId in izdavacModel.Knjige)
            {
                Knjiga knjiga = Knjige.Get(knjigaId);
                knjiga.Izdavac =Izdavaci.Get(izdavac.Id);
            }
            Izdavaci.Save(); */

            return RedirectToAction("Index");
        }
    }
}

Biblioteka.Web/Controllers/KnjigeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Biblioteka.Web.DAL;
using Biblioteka.Web.DAL.Entities;
using Biblioteka.Web.DAL.Repositories;
using Biblioteka.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Biblioteka.Web.Controllers
{
    [Authorize(Roles = "Administrator,UserTest")]
    public class KnjigeController : BaseController
    {
 

        public KnjigeController(IRepository<Knjiga> repository, IRepository<Autor> repositoryA, IRepository<Izdavac> repositoryI)
                                        : base(repository, repositoryA, repositoryI) { }

        public IActionResult Index()
        {
            List<Knjiga> knjige = Knjige.Get().ToList();

            return View(knjige);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int id)
        {
            Knjige.Delete(id);
            Knjige.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Knjiga knjiga = Knjige.Get(id);
            return View(knjiga);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id)
        {
            Knjiga knjiga = Knjige.Get(id);

            return View(knjiga);
        }


        public IActionResult Create()
        {
            List<Izdavac> izdavaci = Izdavaci.Get().ToList();
            List<Autor> autori = Autori.Get().ToList();

            KnjigaModel model = new KnjigaModel()
            {
                listaSvihIzdavaca = izdavaci.Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Ime
                }),
                listaSvihAutora = autori.Select(x => new SelectListItem()
                {
                    Value = x.aId.ToString(),
                    Text = x.Ime
                })
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Knjiga knjiga)
        {
            if (knjiga.kId > 0)
            {
                Knjige.Update(knjiga, knjiga.kId);
            }
            else
            {
                Knjige.Insert(knjiga);
            }
            Knjige.Save();
            return RedirectToAction("Index");
        }

        public IActionResult SaveNew(KnjigaModel knjigaModel)
        {
           
            Knjiga knjiga = new Knjiga()
            {
                kId = knjigaModel.kId,
                Naslov = knjigaModel.Naslov ,
                Cijena = knjigaModel.Cijena,
                Izdavac = Izdavaci.Get(knjigaModel.Izdavac) 
            };
            Knjige.Insert(knjiga);
            Knjige.Save();
            /* implement later(add authbooksrepo :Irepos<authbooks>).. and add here 
            foreach(int autorId in knjigaModel.Autori)
            {
                Unit.AutorKnjiga.Insert(new AutorKnjiga()
                {
                    Autor = Unit.Autori.Get(autorId),
                    Knjiga = knjiga
                });
            }
            Knjige.Save();*/
            return RedirectToAction("Index");
        }
    }
}

Biblioteka.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteka.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Knjige" asp-action="Index">Knjige</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autori" asp-action="Index">Autori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Izdavaci" asp-action="Index">Izdavaci</a>
                        </li>


                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @*If the user is signed-in display Logout link*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" style="width:auto"
                                            class="nav-link btn btn-link py-0">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="role">
                                    CreateRole
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RolesList">Manage Roles</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="login">
                                    Login
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Biblioteka.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>